inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'spec/shared/lib/mrss/**/*'
    - 'vendor/**/*'

Layout:
  Enabled: false

Metrics:
  Enabled: false

RSpec:
  Enabled: false

Style:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Rake/Desc:
  Enabled: false

# Not used by Mongoid
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

# Enable after https://jira.mongodb.org/browse/MONGOID-5180
Rails/Pick:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
