#!/usr/bin/env ruby

require 'fileutils'
require 'active_support/dependencies/autoload'
require 'active_support/core_ext'
require 'yaml'

def gh_path
  File.join(File.dirname(__FILE__), '../.github/workflows/test.yml')
end

def eg_path
  File.join(File.dirname(__FILE__), 'config.yml')
end

def eg_config
  @eg_config ||= YAML.load(File.read(eg_path)).deep_symbolize_keys
end

def axes
  eg_config[:axes].map{|a| a[:id].underscore }
end
